import type {
  Project,
  Document,
  SitePhoto,
  AuditEvent,
  Milestone,
  Alert,
  Trustee,
} from "./types";
import { chainHash, fakeSig, shortHash } from "./hash";

export const PROJECTS: Project[] = [
  {
    id: "kasoa-4bed",
    name: "4-Bedroom Family Home, Kasoa",
    sector: "construction",
    location: "Kasoa, Akweley Hills",
    region: "Central Region",
    diasporaOwner: "Akosua Mensah",
    ownerLocation: "Toronto, Canada",
    managedBy: "Kwame Mensah",
    managedByRelation: "Brother",
    budgetGHS: 685000,
    spentGHS: 412000,
    startDate: "2025-08-14",
    targetCompletion: "2026-09-30",
    progress: 58,
    risk: "med",
    riskScore: 62,
    status: "alert",
    trustScore: 71,
    verifiedMilestones: 4,
    totalMilestones: 8,
    alerts: 2,
    thumbnail: "construction",
    summary:
      "Two-storey family home. Two flags on Q3: cement receipt forensics show font inconsistencies, and a site photo's GPS reads 1.2 km off the parcel.",
  },
  {
    id: "east-legon-plot",
    name: "East Legon Hills Plot (2.5 acres)",
    sector: "real-estate",
    location: "East Legon Hills, Adjiringanor",
    region: "Greater Accra",
    diasporaOwner: "Nana Yaw Boateng",
    ownerLocation: "London, UK",
    managedBy: "Ofori Legal Chambers",
    managedByRelation: "Retained counsel",
    budgetGHS: 1250000,
    spentGHS: 1250000,
    startDate: "2025-04-02",
    targetCompletion: "2025-12-15",
    progress: 92,
    risk: "high",
    riskScore: 84,
    status: "alert",
    trustScore: 48,
    verifiedMilestones: 3,
    totalMilestones: 4,
    alerts: 3,
    thumbnail: "land",
    summary:
      "Title cross-check against Lands Commission registry returned two competing claims on a 0.8-acre overlap. Investigation in progress.",
  },
  {
    id: "tema-civic",
    name: "Civic Hybrid Import (Tema Port)",
    sector: "vehicle-import",
    location: "Tema Port",
    region: "Greater Accra",
    diasporaOwner: "Yaa Asantewaa",
    ownerLocation: "New York, USA",
    managedBy: "Ato Clearing Services",
    managedByRelation: "Licensed clearing agent",
    budgetGHS: 95000,
    spentGHS: 88200,
    startDate: "2026-01-10",
    targetCompletion: "2026-02-20",
    progress: 78,
    risk: "low",
    riskScore: 22,
    status: "active",
    trustScore: 89,
    verifiedMilestones: 5,
    totalMilestones: 6,
    alerts: 0,
    thumbnail: "vehicle",
    summary:
      "Bill of lading, VIN, and GRA duty receipts cross-match. One duty receipt pending blockchain anchor. Vehicle cleared and in transit to inland depot.",
  },
  {
    id: "kumasi-shop",
    name: "Adum Cosmetics Shop Setup",
    sector: "business",
    location: "Adum, Kumasi",
    region: "Ashanti",
    diasporaOwner: "Esi Forson",
    ownerLocation: "Hamburg, Germany",
    managedBy: "Auntie Grace Forson",
    managedByRelation: "Aunt",
    budgetGHS: 142000,
    spentGHS: 96500,
    startDate: "2025-11-01",
    targetCompletion: "2026-03-01",
    progress: 68,
    risk: "med",
    riskScore: 51,
    status: "active",
    trustScore: 76,
    verifiedMilestones: 3,
    totalMilestones: 5,
    alerts: 1,
    thumbnail: "business",
    summary:
      "Shop fitting underway. Suspicious GHS 12,400 'rent top-up' lacks landlord receipt; AI flagged a duplicate transaction signature from October's batch.",
  },
  {
    id: "korle-bu-care",
    name: "Father's Surgery Care (Korle Bu)",
    sector: "medical",
    location: "Korle Bu Teaching Hospital, Accra",
    region: "Greater Accra",
    diasporaOwner: "Kojo Asare",
    ownerLocation: "Sydney, Australia",
    managedBy: "Auntie Adwoa",
    managedByRelation: "Aunt",
    budgetGHS: 38000,
    spentGHS: 31200,
    startDate: "2026-02-04",
    targetCompletion: "2026-03-20",
    progress: 82,
    risk: "low",
    riskScore: 18,
    status: "active",
    trustScore: 93,
    verifiedMilestones: 6,
    totalMilestones: 7,
    alerts: 0,
    thumbnail: "medical",
    summary:
      "All hospital receipts cross-verified against Korle Bu billing portal. Recovery on schedule. Trustee nurse confirms presence on ward rounds.",
  },
  {
    id: "ho-poultry",
    name: "1,200-Bird Poultry Farm, Ho",
    sector: "agriculture",
    location: "Ho, Volta Region",
    region: "Volta",
    diasporaOwner: "Mawuli Agbeko",
    ownerLocation: "Atlanta, USA",
    managedBy: "Cousin Senanu",
    managedByRelation: "Cousin",
    budgetGHS: 78000,
    spentGHS: 52400,
    startDate: "2026-01-20",
    targetCompletion: "2026-06-10",
    progress: 47,
    risk: "low",
    riskScore: 27,
    status: "active",
    trustScore: 84,
    verifiedMilestones: 2,
    totalMilestones: 5,
    alerts: 0,
    thumbnail: "agri",
    summary:
      "Coop construction at 80%. Feed supplier verified. Drone imagery from Trustee A. Yawson confirms structure footprint matches plan.",
  },
];

const baseDate = new Date("2026-05-20T09:00:00Z").getTime();
const minus = (days: number, hours = 0) =>
  new Date(baseDate - days * 86400000 - hours * 3600000).toISOString();

export const DOCUMENTS: Document[] = [
  // Kasoa
  {
    id: "doc-1",
    projectId: "kasoa-4bed",
    name: "Cement Receipt — Diamond Cement (45 bags)",
    type: "receipt",
    uploadedAt: minus(3),
    uploadedBy: "Kwame Mensah",
    authenticityScore: 41,
    flags: ["Inconsistent font (Helvetica → Arial mid-document)", "Pixel-level edits in total field", "Vendor stamp mismatch vs prior 6 receipts"],
    status: "flagged",
    amountGHS: 14400,
    vendor: "Diamond Cement Ghana",
    forensics: {
      metadataIntact: false,
      fontConsistency: 47,
      compressionAnomalies: 6,
      aiGeneratedProbability: 12,
      pixelTampering: 71,
      chainOfCustody: 60,
      crossRefMatched: false,
    },
    hash: shortHash("doc-1"),
  },
  {
    id: "doc-2",
    projectId: "kasoa-4bed",
    name: "Roofing Sheets Invoice — Aluworks",
    type: "invoice",
    uploadedAt: minus(8),
    uploadedBy: "Kwame Mensah",
    authenticityScore: 94,
    flags: [],
    status: "verified",
    amountGHS: 28750,
    vendor: "Aluworks Limited",
    forensics: {
      metadataIntact: true,
      fontConsistency: 98,
      compressionAnomalies: 0,
      aiGeneratedProbability: 3,
      pixelTampering: 2,
      chainOfCustody: 100,
      crossRefMatched: true,
    },
    hash: shortHash("doc-2"),
  },
  {
    id: "doc-3",
    projectId: "kasoa-4bed",
    name: "Architect's BOQ Rev. 3",
    type: "bill-of-quantities",
    uploadedAt: minus(40),
    uploadedBy: "Arch. Mensimah",
    authenticityScore: 100,
    flags: [],
    status: "verified",
    amountGHS: 685000,
    forensics: {
      metadataIntact: true,
      fontConsistency: 100,
      compressionAnomalies: 0,
      aiGeneratedProbability: 1,
      pixelTampering: 0,
      chainOfCustody: 100,
      crossRefMatched: true,
    },
    hash: shortHash("doc-3"),
  },
  {
    id: "doc-4",
    projectId: "kasoa-4bed",
    name: "Building Permit — KEEDA",
    type: "permit",
    uploadedAt: minus(120),
    uploadedBy: "Arch. Mensimah",
    authenticityScore: 99,
    flags: [],
    status: "verified",
    forensics: {
      metadataIntact: true,
      fontConsistency: 100,
      compressionAnomalies: 0,
      aiGeneratedProbability: 1,
      pixelTampering: 0,
      chainOfCustody: 100,
      crossRefMatched: true,
    },
    hash: shortHash("doc-4"),
  },
  // East Legon
  {
    id: "doc-5",
    projectId: "east-legon-plot",
    name: "Indenture — Stool Land Allocation",
    type: "land-title",
    uploadedAt: minus(60),
    uploadedBy: "Ofori Legal Chambers",
    authenticityScore: 62,
    flags: [
      "Lands Commission cross-check: overlapping claim found on 0.8-acre easter portion",
      "Stool elder signature differs from 2 reference samples",
    ],
    status: "flagged",
    forensics: {
      metadataIntact: true,
      fontConsistency: 88,
      compressionAnomalies: 1,
      aiGeneratedProbability: 4,
      pixelTampering: 9,
      chainOfCustody: 70,
      crossRefMatched: false,
    },
    hash: shortHash("doc-5"),
  },
  {
    id: "doc-6",
    projectId: "east-legon-plot",
    name: "Site Plan — Licensed Surveyor",
    type: "site-plan",
    uploadedAt: minus(58),
    uploadedBy: "Surv. K. Boateng",
    authenticityScore: 96,
    flags: [],
    status: "verified",
    forensics: {
      metadataIntact: true,
      fontConsistency: 100,
      compressionAnomalies: 0,
      aiGeneratedProbability: 2,
      pixelTampering: 1,
      chainOfCustody: 100,
      crossRefMatched: true,
    },
    hash: shortHash("doc-6"),
  },
  // Vehicle
  {
    id: "doc-7",
    projectId: "tema-civic",
    name: "Bill of Lading — Maersk",
    type: "delivery-note",
    uploadedAt: minus(20),
    uploadedBy: "Ato Clearing",
    authenticityScore: 99,
    flags: [],
    status: "verified",
    vendor: "Maersk Line",
    forensics: {
      metadataIntact: true,
      fontConsistency: 100,
      compressionAnomalies: 0,
      aiGeneratedProbability: 1,
      pixelTampering: 0,
      chainOfCustody: 100,
      crossRefMatched: true,
    },
    hash: shortHash("doc-7"),
  },
  {
    id: "doc-8",
    projectId: "tema-civic",
    name: "GRA Customs Duty Receipt",
    type: "receipt",
    uploadedAt: minus(7),
    uploadedBy: "Ato Clearing",
    authenticityScore: 97,
    flags: [],
    status: "verified",
    amountGHS: 36800,
    vendor: "Ghana Revenue Authority",
    forensics: {
      metadataIntact: true,
      fontConsistency: 99,
      compressionAnomalies: 0,
      aiGeneratedProbability: 2,
      pixelTampering: 0,
      chainOfCustody: 100,
      crossRefMatched: true,
    },
    hash: shortHash("doc-8"),
  },
  // Business
  {
    id: "doc-9",
    projectId: "kumasi-shop",
    name: "Shop Rent Top-Up — Mr. Adjei",
    type: "receipt",
    uploadedAt: minus(5),
    uploadedBy: "Auntie Grace",
    authenticityScore: 54,
    flags: [
      "No landlord letterhead",
      "Signature near-identical to October top-up (duplicate hash match)",
    ],
    status: "flagged",
    amountGHS: 12400,
    forensics: {
      metadataIntact: false,
      fontConsistency: 70,
      compressionAnomalies: 3,
      aiGeneratedProbability: 19,
      pixelTampering: 22,
      chainOfCustody: 50,
      crossRefMatched: false,
      duplicateOfRef: "doc-9-prev",
    },
    hash: shortHash("doc-9"),
  },
  {
    id: "doc-10",
    projectId: "kumasi-shop",
    name: "Cosmetics Inventory Invoice",
    type: "invoice",
    uploadedAt: minus(12),
    uploadedBy: "Auntie Grace",
    authenticityScore: 91,
    flags: [],
    status: "verified",
    amountGHS: 41200,
    forensics: {
      metadataIntact: true,
      fontConsistency: 96,
      compressionAnomalies: 0,
      aiGeneratedProbability: 3,
      pixelTampering: 1,
      chainOfCustody: 100,
      crossRefMatched: true,
    },
    hash: shortHash("doc-10"),
  },
  // Medical
  {
    id: "doc-11",
    projectId: "korle-bu-care",
    name: "Korle Bu — Pre-Op Bill",
    type: "invoice",
    uploadedAt: minus(15),
    uploadedBy: "Auntie Adwoa",
    authenticityScore: 99,
    flags: [],
    status: "verified",
    amountGHS: 18500,
    vendor: "Korle Bu Teaching Hospital",
    forensics: {
      metadataIntact: true,
      fontConsistency: 100,
      compressionAnomalies: 0,
      aiGeneratedProbability: 1,
      pixelTampering: 0,
      chainOfCustody: 100,
      crossRefMatched: true,
    },
    hash: shortHash("doc-11"),
  },
];

export const SITE_PHOTOS: SitePhoto[] = [
  {
    id: "ph-1",
    projectId: "kasoa-4bed",
    takenAt: minus(2),
    uploadedBy: "Kwame Mensah",
    latitude: 5.5345,
    longitude: -0.4221,
    expectedLat: 5.5421,
    expectedLng: -0.4156,
    distanceM: 1184,
    exifIntact: true,
    sceneMatchScore: 38,
    progressDetected: "Cannot confirm: scene does not match prior verified site",
    aiAnalysis:
      "GPS coordinates place this photo 1.18 km off the registered parcel. Background hills do not match the Akweley reference set. Recommend on-site verification by Trustee.",
    flagged: true,
    caption: "1st floor blockwork in progress",
    hash: shortHash("ph-1"),
  },
  {
    id: "ph-2",
    projectId: "kasoa-4bed",
    takenAt: minus(9),
    uploadedBy: "Kwame Mensah",
    latitude: 5.5419,
    longitude: -0.4159,
    expectedLat: 5.5421,
    expectedLng: -0.4156,
    distanceM: 28,
    exifIntact: true,
    sceneMatchScore: 91,
    progressDetected: "Ground floor lintel cast — matches BOQ stage 4.2",
    aiAnalysis:
      "Site geometry and tree line match prior verified images. Lintel work consistent with expected milestone. Mortar curing visible.",
    flagged: false,
    caption: "Lintel casting complete",
    hash: shortHash("ph-2"),
  },
  {
    id: "ph-3",
    projectId: "kasoa-4bed",
    takenAt: minus(20),
    uploadedBy: "Trustee K. Owusu",
    latitude: 5.542,
    longitude: -0.4156,
    expectedLat: 5.5421,
    expectedLng: -0.4156,
    distanceM: 6,
    exifIntact: true,
    sceneMatchScore: 98,
    progressDetected: "Foundation backfill — milestone 3 confirmed",
    aiAnalysis:
      "Independent trustee verification. Drone overhead + 6 ground angles. Footprint matches architectural drawing within tolerance.",
    flagged: false,
    caption: "Trustee on-site verification visit",
    hash: shortHash("ph-3"),
  },
  {
    id: "ph-4",
    projectId: "east-legon-plot",
    takenAt: minus(4),
    uploadedBy: "Trustee A. Yawson",
    latitude: 5.6512,
    longitude: -0.1421,
    expectedLat: 5.6512,
    expectedLng: -0.1421,
    distanceM: 0,
    exifIntact: true,
    sceneMatchScore: 96,
    progressDetected: "Encroachment detected on eastern boundary",
    aiAnalysis:
      "Foundation trench by 3rd party visible 14 m inside the parcel's eastern boundary. Photographed at 8 angles. Matches claim recorded in Doc-5 cross-check.",
    flagged: true,
    caption: "Encroachment evidence",
    hash: shortHash("ph-4"),
  },
  {
    id: "ph-5",
    projectId: "tema-civic",
    takenAt: minus(7),
    uploadedBy: "Ato Clearing",
    latitude: 5.671,
    longitude: 0.012,
    expectedLat: 5.671,
    expectedLng: 0.012,
    distanceM: 4,
    exifIntact: true,
    sceneMatchScore: 99,
    progressDetected: "Vehicle in customs yard, VIN visible and matches BoL",
    aiAnalysis:
      "Honda Civic VIN JHMFA36286S005211 visible on dashboard plate. Matches Bill of Lading. Cleared for release.",
    flagged: false,
    caption: "Vehicle at Tema Port yard",
    hash: shortHash("ph-5"),
  },
  {
    id: "ph-6",
    projectId: "ho-poultry",
    takenAt: minus(3),
    uploadedBy: "Trustee F. Adeli",
    latitude: 6.612,
    longitude: 0.471,
    expectedLat: 6.612,
    expectedLng: 0.471,
    distanceM: 8,
    exifIntact: true,
    sceneMatchScore: 95,
    progressDetected: "Coop roofing 80% complete, feed silo installed",
    aiAnalysis:
      "Drone imagery + 12 ground photos. Structure dimensions match approved plan: 32m × 9m. Solar panels mounted on south face.",
    flagged: false,
    caption: "Trustee monthly site visit",
    hash: shortHash("ph-6"),
  },
];

export const MILESTONES: Milestone[] = [
  { id: "ms-1", projectId: "kasoa-4bed", name: "Site clearing + setting out", dueDate: "2025-08-30", amountGHS: 22000, status: "released", evidenceCount: 6, verifiedBy: "Trustee K. Owusu" },
  { id: "ms-2", projectId: "kasoa-4bed", name: "Foundation + DPC", dueDate: "2025-10-15", amountGHS: 86000, status: "released", evidenceCount: 9, verifiedBy: "Trustee K. Owusu" },
  { id: "ms-3", projectId: "kasoa-4bed", name: "Ground floor walls + lintels", dueDate: "2025-12-20", amountGHS: 124000, status: "released", evidenceCount: 11, verifiedBy: "Trustee K. Owusu" },
  { id: "ms-4", projectId: "kasoa-4bed", name: "First floor decking", dueDate: "2026-02-28", amountGHS: 140000, status: "verified", evidenceCount: 8, verifiedBy: "Trustee K. Owusu" },
  { id: "ms-5", projectId: "kasoa-4bed", name: "First floor walls", dueDate: "2026-05-30", amountGHS: 118000, status: "disputed", evidenceCount: 3 },
  { id: "ms-6", projectId: "kasoa-4bed", name: "Roofing", dueDate: "2026-07-20", amountGHS: 78000, status: "pending", evidenceCount: 0 },
  { id: "ms-7", projectId: "kasoa-4bed", name: "Plastering + electrical", dueDate: "2026-08-30", amountGHS: 72000, status: "pending", evidenceCount: 0 },
  { id: "ms-8", projectId: "kasoa-4bed", name: "Finishing + handover", dueDate: "2026-09-30", amountGHS: 45000, status: "pending", evidenceCount: 0 },
];

export const ALERTS: Alert[] = [
  {
    id: "al-1",
    projectId: "kasoa-4bed",
    severity: "critical",
    title: "Off-site photo detected",
    detail: "Photo submitted today is 1.18 km from the registered parcel. Trustee dispatch recommended.",
    ts: minus(2, 4),
    category: "site",
  },
  {
    id: "al-2",
    projectId: "kasoa-4bed",
    severity: "warning",
    title: "Cement receipt forensics: 41% authenticity",
    detail: "Font inconsistency and pixel tampering detected on the GHS 14,400 cement receipt.",
    ts: minus(3),
    category: "doc",
  },
  {
    id: "al-3",
    projectId: "east-legon-plot",
    severity: "critical",
    title: "Land title overlap detected",
    detail: "Lands Commission cross-check returned a competing claim on a 0.8-acre overlap. Forensic case opened.",
    ts: minus(11),
    category: "verify",
  },
  {
    id: "al-4",
    projectId: "east-legon-plot",
    severity: "critical",
    title: "Encroachment on parcel",
    detail: "Trustee A. Yawson photographed third-party foundation works 14 m inside eastern boundary.",
    ts: minus(4),
    category: "site",
  },
  {
    id: "al-5",
    projectId: "east-legon-plot",
    severity: "warning",
    title: "Stool elder signature variance",
    detail: "Indenture signature differs from 2 reference samples (variance 22%).",
    ts: minus(58),
    category: "doc",
  },
  {
    id: "al-6",
    projectId: "kumasi-shop",
    severity: "warning",
    title: "Possible duplicate receipt",
    detail: "Rent top-up receipt shares 94% signature hash with October's batch.",
    ts: minus(5),
    category: "doc",
  },
];

// Build a hash-chained audit ledger
function buildLedger(): AuditEvent[] {
  const seed: Array<Omit<AuditEvent, "prevHash" | "hash" | "sig">> = [
    { id: "ev-1", projectId: "kasoa-4bed", ts: minus(140), actor: "Akosua Mensah", action: "Project created — '4-Bedroom Family Home, Kasoa'", category: "system" },
    { id: "ev-2", projectId: "kasoa-4bed", ts: minus(140), actor: "Akosua Mensah", action: "Manager invited: Kwame Mensah (brother)", category: "system" },
    { id: "ev-3", projectId: "kasoa-4bed", ts: minus(125), actor: "Arch. Mensimah", action: "BOQ Rev.3 uploaded & cross-verified", category: "doc", ref: "doc-3" },
    { id: "ev-4", projectId: "kasoa-4bed", ts: minus(120), actor: "Arch. Mensimah", action: "Building permit uploaded — Lands Commission match", category: "doc", ref: "doc-4" },
    { id: "ev-5", projectId: "kasoa-4bed", ts: minus(110), actor: "Akosua Mensah", action: "Escrow funded: GHS 685,000", category: "payment", meta: { amount: 685000 } },
    { id: "ev-6", projectId: "kasoa-4bed", ts: minus(108), actor: "GhanaWatch", action: "Milestone 1 released to Kwame Mensah (GHS 22,000)", category: "milestone" },
    { id: "ev-7", projectId: "kasoa-4bed", ts: minus(95), actor: "Trustee K. Owusu", action: "On-site verification: foundation complete (drone+ground)", category: "trustee", ref: "ph-3" },
    { id: "ev-8", projectId: "kasoa-4bed", ts: minus(94), actor: "GhanaWatch", action: "Milestone 2 released (GHS 86,000)", category: "milestone" },
    { id: "ev-9", projectId: "kasoa-4bed", ts: minus(40), actor: "Trustee K. Owusu", action: "Milestone 3 verified — ground floor lintel cast", category: "trustee", ref: "ph-2" },
    { id: "ev-10", projectId: "kasoa-4bed", ts: minus(20), actor: "Kwame Mensah", action: "Roofing sheets invoice uploaded — verified 94%", category: "doc", ref: "doc-2" },
    { id: "ev-11", projectId: "kasoa-4bed", ts: minus(8), actor: "GhanaWatch AI", action: "Cement receipt flagged — 41% authenticity (font + pixel tampering)", category: "alert", ref: "al-2" },
    { id: "ev-12", projectId: "kasoa-4bed", ts: minus(2, 4), actor: "GhanaWatch AI", action: "Off-site photo flagged — 1.18 km off parcel", category: "alert", ref: "al-1" },
    { id: "ev-13", projectId: "kasoa-4bed", ts: minus(1), actor: "Akosua Mensah", action: "Trustee re-verification requested for Milestone 5", category: "verify" },
  ];
  let prev = "0x000000000000000000";
  const out: AuditEvent[] = [];
  for (const e of seed) {
    const payload = `${e.id}|${e.ts}|${e.actor}|${e.action}|${e.category}|${e.ref ?? ""}`;
    const hash = chainHash(prev, payload);
    out.push({ ...e, prevHash: prev, hash, sig: fakeSig(payload) });
    prev = hash;
  }
  return out;
}

export const AUDIT_EVENTS: AuditEvent[] = buildLedger();

export const TRUSTEES: Trustee[] = [
  {
    id: "tr-1",
    name: "Kojo Owusu, MGhIS",
    profession: "Licensed Quantity Surveyor",
    region: "Greater Accra · Central · Eastern",
    rating: 4.9,
    jobsCompleted: 217,
    specialties: ["Construction milestones", "BOQ validation", "Site progress audits"],
    yearsActive: 14,
    licensed: true,
    verifiedBy: "Ghana Institution of Surveyors",
    feeRange: "GHS 800 — 2,500 / visit",
    avatar: "KO",
    bio: "Independent QS with 14 years auditing diaspora-funded construction. Drone-certified.",
  },
  {
    id: "tr-2",
    name: "Akua Yawson",
    profession: "Licensed Land Surveyor",
    region: "Greater Accra · Volta",
    rating: 4.95,
    jobsCompleted: 154,
    specialties: ["Boundary verification", "Encroachment surveys", "Lands Commission liaison"],
    yearsActive: 11,
    licensed: true,
    verifiedBy: "Ghana Institution of Surveyors",
    feeRange: "GHS 1,200 — 4,000 / parcel",
    avatar: "AY",
    bio: "Specialist in title-overlap forensics. Authored 9 court-admitted survey reports.",
  },
  {
    id: "tr-3",
    name: "Esi Ofori, Esq.",
    profession: "Property & Conveyancing Lawyer",
    region: "All regions",
    rating: 4.85,
    jobsCompleted: 96,
    specialties: ["Title due diligence", "Indenture review", "Litigation risk assessment"],
    yearsActive: 9,
    licensed: true,
    verifiedBy: "General Legal Council of Ghana",
    feeRange: "GHS 1,500 — 6,000 / matter",
    avatar: "EO",
    bio: "Conveyancing counsel with deep Lands Commission access.",
  },
  {
    id: "tr-4",
    name: "Dr. Nana Akoto",
    profession: "Medical Care Coordinator",
    region: "Greater Accra · Ashanti",
    rating: 4.97,
    jobsCompleted: 312,
    specialties: ["Hospital bill verification", "Ward visit attestation", "Care coordination"],
    yearsActive: 18,
    licensed: true,
    verifiedBy: "Medical & Dental Council",
    feeRange: "GHS 400 — 1,200 / visit",
    avatar: "NA",
    bio: "Family medicine physician offering diaspora medical oversight.",
  },
  {
    id: "tr-5",
    name: "Ato Bekoe",
    profession: "Licensed Customs Clearing Agent",
    region: "Tema · Takoradi · KIA",
    rating: 4.8,
    jobsCompleted: 488,
    specialties: ["Vehicle import", "Duty calculation audit", "Bonded warehouse"],
    yearsActive: 16,
    licensed: true,
    verifiedBy: "GRA / Customs Division",
    feeRange: "GHS 600 — 3,500 / shipment",
    avatar: "AB",
    bio: "16 years clearing diaspora vehicle imports. GRA-licensed agent #CG-2148.",
  },
  {
    id: "tr-6",
    name: "Fafa Adeli",
    profession: "Agricultural Extension Officer",
    region: "Volta · Eastern · Oti",
    rating: 4.88,
    jobsCompleted: 71,
    specialties: ["Poultry & livestock", "Farm audits", "Yield forecasting"],
    yearsActive: 8,
    licensed: true,
    verifiedBy: "Ministry of Food & Agriculture",
    feeRange: "GHS 500 — 1,800 / visit",
    avatar: "FA",
    bio: "MoFA-trained extension officer with drone surveying skills.",
  },
];

export const getProject = (id: string) => PROJECTS.find((p) => p.id === id);
export const getDocsByProject = (id: string) => DOCUMENTS.filter((d) => d.projectId === id);
export const getPhotosByProject = (id: string) => SITE_PHOTOS.filter((p) => p.projectId === id);
export const getMilestonesByProject = (id: string) => MILESTONES.filter((m) => m.projectId === id);
export const getAlertsByProject = (id: string) => ALERTS.filter((a) => a.projectId === id);
export const getAuditByProject = (id: string) =>
  AUDIT_EVENTS.filter((e) => e.projectId === id).sort((a, b) => (a.ts < b.ts ? 1 : -1));

// Platform-wide stats
export const PLATFORM_STATS = {
  remittancesTracked2025GHS: 18_400_000,
  fraudPrevented2025GHS: 2_180_000,
  documentsAnalyzed: 14_872,
  flagsRaised: 612,
  trusteesActive: 1_240,
  diasporaUsers: 8_950,
  projectsActive: 1_487,
  forensicCasesOpen: 38,
  countriesServed: 47,
};
