import type {
  Project,
  Document,
  SitePhoto,
  AuditEvent,
  Milestone,
  Alert,
  Trustee,
  ForensicCase,
  FraudPattern,
  Benchmark,
  Notification,
  Region,
  HumanReview,
  Signatory,
  TrusteeApplication,
  LiveEvent,
  HometownRoom,
} from "./types";
import { chainHash, fakeSig, shortHash } from "./hash";

const baseDate = new Date("2026-05-20T09:00:00Z").getTime();
const minus = (days: number, hours = 0) =>
  new Date(baseDate - days * 86400000 - hours * 3600000).toISOString();

function genSeries(days: number, start: number, vol: number, drift = 0): { d: string; v: number }[] {
  const out: { d: string; v: number }[] = [];
  let v = start;
  for (let i = days; i >= 0; i--) {
    v = Math.max(0, Math.min(100, v + (Math.sin(i / 3) * vol) / 2 + drift + (i % 5 === 0 ? -vol / 3 : vol / 6)));
    out.push({ d: minus(i).slice(0, 10), v: Math.round(v) });
  }
  return out;
}

export const PROJECTS: Project[] = [
  {
    id: "kasoa-4bed",
    name: "4-Bedroom Family Home, Kasoa",
    sector: "construction",
    location: "Kasoa, Akweley Hills",
    region: "Central",
    lat: 5.5421,
    lng: -0.4156,
    diasporaOwner: "Akosua Mensah",
    ownerLocation: "Toronto, Canada",
    managedBy: "Kwame Mensah",
    managedByRelation: "Brother",
    budgetGHS: 685000,
    spentGHS: 412000,
    startDate: "2025-08-14",
    targetCompletion: "2026-09-30",
    progress: 58,
    risk: "med",
    riskScore: 62,
    status: "alert",
    trustScore: 71,
    verifiedMilestones: 4,
    totalMilestones: 8,
    alerts: 2,
    thumbnail: "construction",
    summary:
      "Two-storey family home. Two flags on Q3: cement receipt forensics show font inconsistencies, and a site photo's GPS reads 1.2 km off the parcel.",
    trustHistory: genSeries(60, 92, 5, -0.4),
    riskHistory: genSeries(60, 22, 6, 0.6),
  },
  {
    id: "east-legon-plot",
    name: "East Legon Hills Plot (2.5 acres)",
    sector: "real-estate",
    location: "East Legon Hills, Adjiringanor",
    region: "Greater Accra",
    lat: 5.6512,
    lng: -0.1421,
    diasporaOwner: "Nana Yaw Boateng",
    ownerLocation: "London, UK",
    managedBy: "Ofori Legal Chambers",
    managedByRelation: "Retained counsel",
    budgetGHS: 1250000,
    spentGHS: 1250000,
    startDate: "2025-04-02",
    targetCompletion: "2025-12-15",
    progress: 92,
    risk: "high",
    riskScore: 84,
    status: "alert",
    trustScore: 48,
    verifiedMilestones: 3,
    totalMilestones: 4,
    alerts: 3,
    thumbnail: "land",
    summary:
      "Title cross-check against Lands Commission registry returned two competing claims on a 0.8-acre overlap. Investigation in progress.",
    trustHistory: genSeries(120, 82, 6, -0.3),
    riskHistory: genSeries(120, 14, 8, 0.7),
  },
  {
    id: "tema-civic",
    name: "Civic Hybrid Import (Tema Port)",
    sector: "vehicle-import",
    location: "Tema Port",
    region: "Greater Accra",
    lat: 5.671,
    lng: 0.012,
    diasporaOwner: "Yaa Asantewaa",
    ownerLocation: "New York, USA",
    managedBy: "Ato Clearing Services",
    managedByRelation: "Licensed clearing agent",
    budgetGHS: 95000,
    spentGHS: 88200,
    startDate: "2026-01-10",
    targetCompletion: "2026-02-20",
    progress: 78,
    risk: "low",
    riskScore: 22,
    status: "active",
    trustScore: 89,
    verifiedMilestones: 5,
    totalMilestones: 6,
    alerts: 0,
    thumbnail: "vehicle",
    summary:
      "Bill of lading, VIN, and GRA duty receipts cross-match. One duty receipt pending blockchain anchor. Vehicle cleared and in transit to inland depot.",
    trustHistory: genSeries(40, 70, 4, 0.5),
    riskHistory: genSeries(40, 45, 3, -0.6),
  },
  {
    id: "kumasi-shop",
    name: "Adum Cosmetics Shop Setup",
    sector: "business",
    location: "Adum, Kumasi",
    region: "Ashanti",
    lat: 6.6884,
    lng: -1.6244,
    diasporaOwner: "Esi Forson",
    ownerLocation: "Hamburg, Germany",
    managedBy: "Auntie Grace Forson",
    managedByRelation: "Aunt",
    budgetGHS: 142000,
    spentGHS: 96500,
    startDate: "2025-11-01",
    targetCompletion: "2026-03-01",
    progress: 68,
    risk: "med",
    riskScore: 51,
    status: "active",
    trustScore: 76,
    verifiedMilestones: 3,
    totalMilestones: 5,
    alerts: 1,
    thumbnail: "business",
    summary:
      "Shop fitting underway. Suspicious GHS 12,400 'rent top-up' lacks landlord receipt; AI flagged a duplicate transaction signature from October's batch.",
    trustHistory: genSeries(80, 90, 5, -0.2),
    riskHistory: genSeries(80, 18, 5, 0.4),
  },
  {
    id: "korle-bu-care",
    name: "Father's Surgery Care (Korle Bu)",
    sector: "medical",
    location: "Korle Bu Teaching Hospital, Accra",
    region: "Greater Accra",
    lat: 5.5358,
    lng: -0.2295,
    diasporaOwner: "Kojo Asare",
    ownerLocation: "Sydney, Australia",
    managedBy: "Auntie Adwoa",
    managedByRelation: "Aunt",
    budgetGHS: 38000,
    spentGHS: 31200,
    startDate: "2026-02-04",
    targetCompletion: "2026-03-20",
    progress: 82,
    risk: "low",
    riskScore: 18,
    status: "active",
    trustScore: 93,
    verifiedMilestones: 6,
    totalMilestones: 7,
    alerts: 0,
    thumbnail: "medical",
    summary:
      "All hospital receipts cross-verified against Korle Bu billing portal. Recovery on schedule. Trustee nurse confirms presence on ward rounds.",
    trustHistory: genSeries(30, 80, 4, 0.4),
    riskHistory: genSeries(30, 35, 3, -0.5),
  },
  {
    id: "ho-poultry",
    name: "1,200-Bird Poultry Farm, Ho",
    sector: "agriculture",
    location: "Ho, Volta Region",
    region: "Volta",
    lat: 6.612,
    lng: 0.471,
    diasporaOwner: "Mawuli Agbeko",
    ownerLocation: "Atlanta, USA",
    managedBy: "Cousin Senanu",
    managedByRelation: "Cousin",
    budgetGHS: 78000,
    spentGHS: 52400,
    startDate: "2026-01-20",
    targetCompletion: "2026-06-10",
    progress: 47,
    risk: "low",
    riskScore: 27,
    status: "active",
    trustScore: 84,
    verifiedMilestones: 2,
    totalMilestones: 5,
    alerts: 0,
    thumbnail: "agri",
    summary:
      "Coop construction at 80%. Feed supplier verified. Drone imagery from Trustee A. Yawson confirms structure footprint matches plan.",
    trustHistory: genSeries(50, 78, 4, 0.2),
    riskHistory: genSeries(50, 30, 3, -0.1),
  },
  {
    id: "takoradi-funeral",
    name: "Late Aunt Akua's Funeral Rites",
    sector: "funeral",
    location: "Takoradi, Western Region",
    region: "Western",
    lat: 4.8845,
    lng: -1.7554,
    diasporaOwner: "Kwesi Nkrumah",
    ownerLocation: "Bristol, UK",
    managedBy: "Cousin Esinam",
    managedByRelation: "Cousin",
    budgetGHS: 48000,
    spentGHS: 28000,
    startDate: "2026-04-10",
    targetCompletion: "2026-06-05",
    progress: 60,
    risk: "med",
    riskScore: 55,
    status: "alert",
    trustScore: 70,
    verifiedMilestones: 2,
    totalMilestones: 4,
    alerts: 1,
    thumbnail: "funeral",
    summary:
      "Canopy and PA system invoices are 38% above benchmark. Vendor MoMo IDs cannot be confirmed. Recommended trustee attendance at the planning meeting.",
    trustHistory: genSeries(40, 86, 5, -0.3),
    riskHistory: genSeries(40, 20, 4, 0.5),
  },
  {
    id: "tamale-school",
    name: "Daughter's SHS Boarding Fees + Books",
    sector: "education",
    location: "Tamale Secondary School",
    region: "Northern",
    lat: 9.4008,
    lng: -0.8393,
    diasporaOwner: "Hawa Mahama",
    ownerLocation: "Manchester, UK",
    managedBy: "Bro. Yakubu",
    managedByRelation: "Uncle",
    budgetGHS: 14500,
    spentGHS: 9200,
    startDate: "2026-01-15",
    targetCompletion: "2026-07-30",
    progress: 64,
    risk: "low",
    riskScore: 15,
    status: "active",
    trustScore: 95,
    verifiedMilestones: 3,
    totalMilestones: 4,
    alerts: 0,
    thumbnail: "education",
    summary:
      "School fees verified against GES portal. Books invoice within benchmark. Attendance attested by school bursar.",
    trustHistory: genSeries(30, 80, 3, 0.5),
    riskHistory: genSeries(30, 25, 3, -0.3),
  },
];

export const DOCUMENTS: Document[] = [
  {
    id: "doc-1",
    projectId: "kasoa-4bed",
    name: "Cement Receipt — Diamond Cement (45 bags)",
    type: "receipt",
    uploadedAt: minus(3),
    uploadedBy: "Kwame Mensah",
    authenticityScore: 41,
    flags: [
      "Inconsistent font (Helvetica → Arial mid-document)",
      "Pixel-level edits in total field",
      "Vendor stamp mismatch vs prior 6 receipts",
    ],
    status: "flagged",
    amountGHS: 14400,
    vendor: "Diamond Cement Ghana",
    forensics: {
      metadataIntact: false,
      fontConsistency: 47,
      compressionAnomalies: 6,
      aiGeneratedProbability: 12,
      pixelTampering: 71,
      chainOfCustody: 60,
      crossRefMatched: false,
    },
    hash: shortHash("doc-1"),
  },
  {
    id: "doc-2",
    projectId: "kasoa-4bed",
    name: "Roofing Sheets Invoice — Aluworks",
    type: "invoice",
    uploadedAt: minus(8),
    uploadedBy: "Kwame Mensah",
    authenticityScore: 94,
    flags: [],
    status: "verified",
    amountGHS: 28750,
    vendor: "Aluworks Limited",
    forensics: {
      metadataIntact: true,
      fontConsistency: 98,
      compressionAnomalies: 0,
      aiGeneratedProbability: 3,
      pixelTampering: 2,
      chainOfCustody: 100,
      crossRefMatched: true,
    },
    hash: shortHash("doc-2"),
  },
  {
    id: "doc-3",
    projectId: "kasoa-4bed",
    name: "Architect's BOQ Rev. 3",
    type: "bill-of-quantities",
    uploadedAt: minus(40),
    uploadedBy: "Arch. Mensimah",
    authenticityScore: 100,
    flags: [],
    status: "verified",
    amountGHS: 685000,
    forensics: {
      metadataIntact: true,
      fontConsistency: 100,
      compressionAnomalies: 0,
      aiGeneratedProbability: 1,
      pixelTampering: 0,
      chainOfCustody: 100,
      crossRefMatched: true,
    },
    hash: shortHash("doc-3"),
  },
  {
    id: "doc-4",
    projectId: "kasoa-4bed",
    name: "Building Permit — KEEDA",
    type: "permit",
    uploadedAt: minus(120),
    uploadedBy: "Arch. Mensimah",
    authenticityScore: 99,
    flags: [],
    status: "verified",
    forensics: {
      metadataIntact: true,
      fontConsistency: 100,
      compressionAnomalies: 0,
      aiGeneratedProbability: 1,
      pixelTampering: 0,
      chainOfCustody: 100,
      crossRefMatched: true,
    },
    hash: shortHash("doc-4"),
  },
  {
    id: "doc-5",
    projectId: "east-legon-plot",
    name: "Indenture — Stool Land Allocation",
    type: "land-title",
    uploadedAt: minus(60),
    uploadedBy: "Ofori Legal Chambers",
    authenticityScore: 62,
    flags: [
      "Lands Commission cross-check: overlapping claim found on 0.8-acre easter portion",
      "Stool elder signature differs from 2 reference samples",
    ],
    status: "flagged",
    forensics: {
      metadataIntact: true,
      fontConsistency: 88,
      compressionAnomalies: 1,
      aiGeneratedProbability: 4,
      pixelTampering: 9,
      chainOfCustody: 70,
      crossRefMatched: false,
    },
    hash: shortHash("doc-5"),
  },
  {
    id: "doc-6",
    projectId: "east-legon-plot",
    name: "Site Plan — Licensed Surveyor",
    type: "site-plan",
    uploadedAt: minus(58),
    uploadedBy: "Surv. K. Boateng",
    authenticityScore: 96,
    flags: [],
    status: "verified",
    forensics: {
      metadataIntact: true,
      fontConsistency: 100,
      compressionAnomalies: 0,
      aiGeneratedProbability: 2,
      pixelTampering: 1,
      chainOfCustody: 100,
      crossRefMatched: true,
    },
    hash: shortHash("doc-6"),
  },
  {
    id: "doc-7",
    projectId: "tema-civic",
    name: "Bill of Lading — Maersk",
    type: "delivery-note",
    uploadedAt: minus(20),
    uploadedBy: "Ato Clearing",
    authenticityScore: 99,
    flags: [],
    status: "verified",
    vendor: "Maersk Line",
    forensics: {
      metadataIntact: true,
      fontConsistency: 100,
      compressionAnomalies: 0,
      aiGeneratedProbability: 1,
      pixelTampering: 0,
      chainOfCustody: 100,
      crossRefMatched: true,
    },
    hash: shortHash("doc-7"),
  },
  {
    id: "doc-8",
    projectId: "tema-civic",
    name: "GRA Customs Duty Receipt",
    type: "receipt",
    uploadedAt: minus(7),
    uploadedBy: "Ato Clearing",
    authenticityScore: 97,
    flags: [],
    status: "verified",
    amountGHS: 36800,
    vendor: "Ghana Revenue Authority",
    forensics: {
      metadataIntact: true,
      fontConsistency: 99,
      compressionAnomalies: 0,
      aiGeneratedProbability: 2,
      pixelTampering: 0,
      chainOfCustody: 100,
      crossRefMatched: true,
    },
    hash: shortHash("doc-8"),
  },
  {
    id: "doc-9",
    projectId: "kumasi-shop",
    name: "Shop Rent Top-Up — Mr. Adjei",
    type: "receipt",
    uploadedAt: minus(5),
    uploadedBy: "Auntie Grace",
    authenticityScore: 54,
    flags: [
      "No landlord letterhead",
      "Signature near-identical to October top-up (duplicate hash match)",
    ],
    status: "flagged",
    amountGHS: 12400,
    forensics: {
      metadataIntact: false,
      fontConsistency: 70,
      compressionAnomalies: 3,
      aiGeneratedProbability: 19,
      pixelTampering: 22,
      chainOfCustody: 50,
      crossRefMatched: false,
      duplicateOfRef: "doc-9-prev",
    },
    hash: shortHash("doc-9"),
  },
  {
    id: "doc-10",
    projectId: "kumasi-shop",
    name: "Cosmetics Inventory Invoice",
    type: "invoice",
    uploadedAt: minus(12),
    uploadedBy: "Auntie Grace",
    authenticityScore: 91,
    flags: [],
    status: "verified",
    amountGHS: 41200,
    forensics: {
      metadataIntact: true,
      fontConsistency: 96,
      compressionAnomalies: 0,
      aiGeneratedProbability: 3,
      pixelTampering: 1,
      chainOfCustody: 100,
      crossRefMatched: true,
    },
    hash: shortHash("doc-10"),
  },
  {
    id: "doc-11",
    projectId: "korle-bu-care",
    name: "Korle Bu — Pre-Op Bill",
    type: "invoice",
    uploadedAt: minus(15),
    uploadedBy: "Auntie Adwoa",
    authenticityScore: 99,
    flags: [],
    status: "verified",
    amountGHS: 18500,
    vendor: "Korle Bu Teaching Hospital",
    forensics: {
      metadataIntact: true,
      fontConsistency: 100,
      compressionAnomalies: 0,
      aiGeneratedProbability: 1,
      pixelTampering: 0,
      chainOfCustody: 100,
      crossRefMatched: true,
    },
    hash: shortHash("doc-11"),
  },
  {
    id: "doc-12",
    projectId: "takoradi-funeral",
    name: "Canopy & PA System Quote",
    type: "invoice",
    uploadedAt: minus(6),
    uploadedBy: "Cousin Esinam",
    authenticityScore: 58,
    flags: [
      "Quoted GHS 8,400 — 38% above regional benchmark (GHS 6,080 median)",
      "Vendor MoMo merchant ID does not resolve",
    ],
    status: "flagged",
    amountGHS: 8400,
    forensics: {
      metadataIntact: false,
      fontConsistency: 78,
      compressionAnomalies: 2,
      aiGeneratedProbability: 8,
      pixelTampering: 18,
      chainOfCustody: 55,
      crossRefMatched: false,
    },
    hash: shortHash("doc-12"),
  },
];

export const SITE_PHOTOS: SitePhoto[] = [
  {
    id: "ph-1",
    projectId: "kasoa-4bed",
    takenAt: minus(2),
    uploadedBy: "Kwame Mensah",
    latitude: 5.5345,
    longitude: -0.4221,
    expectedLat: 5.5421,
    expectedLng: -0.4156,
    distanceM: 1184,
    exifIntact: true,
    sceneMatchScore: 38,
    progressDetected: "Cannot confirm: scene does not match prior verified site",
    aiAnalysis:
      "GPS coordinates place this photo 1.18 km off the registered parcel. Background hills do not match the Akweley reference set. Recommend on-site verification by Trustee.",
    flagged: true,
    caption: "1st floor blockwork in progress",
    hash: shortHash("ph-1"),
  },
  {
    id: "ph-2",
    projectId: "kasoa-4bed",
    takenAt: minus(9),
    uploadedBy: "Kwame Mensah",
    latitude: 5.5419,
    longitude: -0.4159,
    expectedLat: 5.5421,
    expectedLng: -0.4156,
    distanceM: 28,
    exifIntact: true,
    sceneMatchScore: 91,
    progressDetected: "Ground floor lintel cast — matches BOQ stage 4.2",
    aiAnalysis:
      "Site geometry and tree line match prior verified images. Lintel work consistent with expected milestone. Mortar curing visible.",
    flagged: false,
    caption: "Lintel casting complete",
    hash: shortHash("ph-2"),
  },
  {
    id: "ph-3",
    projectId: "kasoa-4bed",
    takenAt: minus(20),
    uploadedBy: "Trustee K. Owusu",
    latitude: 5.542,
    longitude: -0.4156,
    expectedLat: 5.5421,
    expectedLng: -0.4156,
    distanceM: 6,
    exifIntact: true,
    sceneMatchScore: 98,
    progressDetected: "Foundation backfill — milestone 3 confirmed",
    aiAnalysis:
      "Independent trustee verification. Drone overhead + 6 ground angles. Footprint matches architectural drawing within tolerance.",
    flagged: false,
    caption: "Trustee on-site verification visit",
    hash: shortHash("ph-3"),
  },
  {
    id: "ph-4",
    projectId: "east-legon-plot",
    takenAt: minus(4),
    uploadedBy: "Trustee A. Yawson",
    latitude: 5.6512,
    longitude: -0.1421,
    expectedLat: 5.6512,
    expectedLng: -0.1421,
    distanceM: 0,
    exifIntact: true,
    sceneMatchScore: 96,
    progressDetected: "Encroachment detected on eastern boundary",
    aiAnalysis:
      "Foundation trench by 3rd party visible 14 m inside the parcel's eastern boundary. Photographed at 8 angles. Matches claim recorded in Doc-5 cross-check.",
    flagged: true,
    caption: "Encroachment evidence",
    hash: shortHash("ph-4"),
  },
  {
    id: "ph-5",
    projectId: "tema-civic",
    takenAt: minus(7),
    uploadedBy: "Ato Clearing",
    latitude: 5.671,
    longitude: 0.012,
    expectedLat: 5.671,
    expectedLng: 0.012,
    distanceM: 4,
    exifIntact: true,
    sceneMatchScore: 99,
    progressDetected: "Vehicle in customs yard, VIN visible and matches BoL",
    aiAnalysis:
      "Honda Civic VIN JHMFA36286S005211 visible on dashboard plate. Matches Bill of Lading. Cleared for release.",
    flagged: false,
    caption: "Vehicle at Tema Port yard",
    hash: shortHash("ph-5"),
  },
  {
    id: "ph-6",
    projectId: "ho-poultry",
    takenAt: minus(3),
    uploadedBy: "Trustee F. Adeli",
    latitude: 6.612,
    longitude: 0.471,
    expectedLat: 6.612,
    expectedLng: 0.471,
    distanceM: 8,
    exifIntact: true,
    sceneMatchScore: 95,
    progressDetected: "Coop roofing 80% complete, feed silo installed",
    aiAnalysis:
      "Drone imagery + 12 ground photos. Structure dimensions match approved plan: 32m × 9m. Solar panels mounted on south face.",
    flagged: false,
    caption: "Trustee monthly site visit",
    hash: shortHash("ph-6"),
  },
];

export const MILESTONES: Milestone[] = [
  { id: "ms-1", projectId: "kasoa-4bed", name: "Site clearing + setting out", dueDate: "2025-08-30", amountGHS: 22000, status: "released", evidenceCount: 6, verifiedBy: "Trustee K. Owusu" },
  { id: "ms-2", projectId: "kasoa-4bed", name: "Foundation + DPC", dueDate: "2025-10-15", amountGHS: 86000, status: "released", evidenceCount: 9, verifiedBy: "Trustee K. Owusu" },
  { id: "ms-3", projectId: "kasoa-4bed", name: "Ground floor walls + lintels", dueDate: "2025-12-20", amountGHS: 124000, status: "released", evidenceCount: 11, verifiedBy: "Trustee K. Owusu" },
  { id: "ms-4", projectId: "kasoa-4bed", name: "First floor decking", dueDate: "2026-02-28", amountGHS: 140000, status: "verified", evidenceCount: 8, verifiedBy: "Trustee K. Owusu" },
  { id: "ms-5", projectId: "kasoa-4bed", name: "First floor walls", dueDate: "2026-05-30", amountGHS: 118000, status: "disputed", evidenceCount: 3 },
  { id: "ms-6", projectId: "kasoa-4bed", name: "Roofing", dueDate: "2026-07-20", amountGHS: 78000, status: "pending", evidenceCount: 0 },
  { id: "ms-7", projectId: "kasoa-4bed", name: "Plastering + electrical", dueDate: "2026-08-30", amountGHS: 72000, status: "pending", evidenceCount: 0 },
  { id: "ms-8", projectId: "kasoa-4bed", name: "Finishing + handover", dueDate: "2026-09-30", amountGHS: 45000, status: "pending", evidenceCount: 0 },
];

export const ALERTS: Alert[] = [
  {
    id: "al-1",
    projectId: "kasoa-4bed",
    severity: "critical",
    title: "Off-site photo detected",
    detail: "Photo submitted today is 1.18 km from the registered parcel. Trustee dispatch recommended.",
    ts: minus(2, 4),
    category: "site",
  },
  {
    id: "al-2",
    projectId: "kasoa-4bed",
    severity: "warning",
    title: "Cement receipt forensics: 41% authenticity",
    detail: "Font inconsistency and pixel tampering detected on the GHS 14,400 cement receipt.",
    ts: minus(3),
    category: "doc",
  },
  {
    id: "al-3",
    projectId: "east-legon-plot",
    severity: "critical",
    title: "Land title overlap detected",
    detail: "Lands Commission cross-check returned a competing claim on a 0.8-acre overlap. Forensic case opened.",
    ts: minus(11),
    category: "verify",
  },
  {
    id: "al-4",
    projectId: "east-legon-plot",
    severity: "critical",
    title: "Encroachment on parcel",
    detail: "Trustee A. Yawson photographed third-party foundation works 14 m inside eastern boundary.",
    ts: minus(4),
    category: "site",
  },
  {
    id: "al-5",
    projectId: "east-legon-plot",
    severity: "warning",
    title: "Stool elder signature variance",
    detail: "Indenture signature differs from 2 reference samples (variance 22%).",
    ts: minus(58),
    category: "doc",
  },
  {
    id: "al-6",
    projectId: "kumasi-shop",
    severity: "warning",
    title: "Possible duplicate receipt",
    detail: "Rent top-up receipt shares 94% signature hash with October's batch.",
    ts: minus(5),
    category: "doc",
  },
  {
    id: "al-7",
    projectId: "takoradi-funeral",
    severity: "warning",
    title: "Canopy quote 38% above benchmark",
    detail: "Quoted GHS 8,400 vs regional median GHS 6,080.",
    ts: minus(6),
    category: "doc",
  },
];

function buildLedger(): AuditEvent[] {
  const seed: Array<Omit<AuditEvent, "prevHash" | "hash" | "sig">> = [
    { id: "ev-1", projectId: "kasoa-4bed", ts: minus(140), actor: "Akosua Mensah", action: "Project created — '4-Bedroom Family Home, Kasoa'", category: "system" },
    { id: "ev-2", projectId: "kasoa-4bed", ts: minus(140), actor: "Akosua Mensah", action: "Manager invited: Kwame Mensah (brother)", category: "system" },
    { id: "ev-3", projectId: "kasoa-4bed", ts: minus(125), actor: "Arch. Mensimah", action: "BOQ Rev.3 uploaded & cross-verified", category: "doc", ref: "doc-3" },
    { id: "ev-4", projectId: "kasoa-4bed", ts: minus(120), actor: "Arch. Mensimah", action: "Building permit uploaded — Lands Commission match", category: "doc", ref: "doc-4" },
    { id: "ev-5", projectId: "kasoa-4bed", ts: minus(110), actor: "Akosua Mensah", action: "Escrow funded: GHS 685,000", category: "payment", meta: { amount: 685000 } },
    { id: "ev-6", projectId: "kasoa-4bed", ts: minus(108), actor: "GhanaWatch", action: "Milestone 1 released to Kwame Mensah (GHS 22,000)", category: "milestone" },
    { id: "ev-7", projectId: "kasoa-4bed", ts: minus(95), actor: "Trustee K. Owusu", action: "On-site verification: foundation complete (drone+ground)", category: "trustee", ref: "ph-3" },
    { id: "ev-8", projectId: "kasoa-4bed", ts: minus(94), actor: "GhanaWatch", action: "Milestone 2 released (GHS 86,000)", category: "milestone" },
    { id: "ev-9", projectId: "kasoa-4bed", ts: minus(40), actor: "Trustee K. Owusu", action: "Milestone 3 verified — ground floor lintel cast", category: "trustee", ref: "ph-2" },
    { id: "ev-10", projectId: "kasoa-4bed", ts: minus(20), actor: "Kwame Mensah", action: "Roofing sheets invoice uploaded — verified 94%", category: "doc", ref: "doc-2" },
    { id: "ev-11", projectId: "kasoa-4bed", ts: minus(8), actor: "GhanaWatch AI", action: "Cement receipt flagged — 41% authenticity (font + pixel tampering)", category: "alert", ref: "al-2" },
    { id: "ev-12", projectId: "kasoa-4bed", ts: minus(2, 4), actor: "GhanaWatch AI", action: "Off-site photo flagged — 1.18 km off parcel", category: "alert", ref: "al-1" },
    { id: "ev-13", projectId: "kasoa-4bed", ts: minus(1), actor: "Akosua Mensah", action: "Trustee re-verification requested for Milestone 5", category: "verify" },
  ];
  let prev = "0x000000000000000000";
  const out: AuditEvent[] = [];
  for (const e of seed) {
    const payload = `${e.id}|${e.ts}|${e.actor}|${e.action}|${e.category}|${e.ref ?? ""}`;
    const hash = chainHash(prev, payload);
    out.push({ ...e, prevHash: prev, hash, sig: fakeSig(payload) });
    prev = hash;
  }
  return out;
}

export const AUDIT_EVENTS: AuditEvent[] = buildLedger();

export const TRUSTEES: Trustee[] = [
  {
    id: "tr-1",
    name: "Kojo Owusu, MGhIS",
    profession: "Licensed Quantity Surveyor",
    region: "Greater Accra · Central · Eastern",
    rating: 4.9,
    jobsCompleted: 217,
    specialties: ["Construction milestones", "BOQ validation", "Site progress audits"],
    yearsActive: 14,
    licensed: true,
    verifiedBy: "Ghana Institution of Surveyors",
    feeRange: "GHS 800 — 2,500 / visit",
    avatar: "KO",
    bio: "Independent QS with 14 years auditing diaspora-funded construction. Drone-certified.",
    responseHours: 18,
    availableNow: true,
  },
  {
    id: "tr-2",
    name: "Akua Yawson",
    profession: "Licensed Land Surveyor",
    region: "Greater Accra · Volta",
    rating: 4.95,
    jobsCompleted: 154,
    specialties: ["Boundary verification", "Encroachment surveys", "Lands Commission liaison"],
    yearsActive: 11,
    licensed: true,
    verifiedBy: "Ghana Institution of Surveyors",
    feeRange: "GHS 1,200 — 4,000 / parcel",
    avatar: "AY",
    bio: "Specialist in title-overlap forensics. Authored 9 court-admitted survey reports.",
    responseHours: 12,
    availableNow: true,
  },
  {
    id: "tr-3",
    name: "Esi Ofori, Esq.",
    profession: "Property & Conveyancing Lawyer",
    region: "All regions",
    rating: 4.85,
    jobsCompleted: 96,
    specialties: ["Title due diligence", "Indenture review", "Litigation risk assessment"],
    yearsActive: 9,
    licensed: true,
    verifiedBy: "General Legal Council of Ghana",
    feeRange: "GHS 1,500 — 6,000 / matter",
    avatar: "EO",
    bio: "Conveyancing counsel with deep Lands Commission access.",
    responseHours: 24,
    availableNow: false,
  },
  {
    id: "tr-4",
    name: "Dr. Nana Akoto",
    profession: "Medical Care Coordinator",
    region: "Greater Accra · Ashanti",
    rating: 4.97,
    jobsCompleted: 312,
    specialties: ["Hospital bill verification", "Ward visit attestation", "Care coordination"],
    yearsActive: 18,
    licensed: true,
    verifiedBy: "Medical & Dental Council",
    feeRange: "GHS 400 — 1,200 / visit",
    avatar: "NA",
    bio: "Family medicine physician offering diaspora medical oversight.",
    responseHours: 6,
    availableNow: true,
  },
  {
    id: "tr-5",
    name: "Ato Bekoe",
    profession: "Licensed Customs Clearing Agent",
    region: "Tema · Takoradi · KIA",
    rating: 4.8,
    jobsCompleted: 488,
    specialties: ["Vehicle import", "Duty calculation audit", "Bonded warehouse"],
    yearsActive: 16,
    licensed: true,
    verifiedBy: "GRA / Customs Division",
    feeRange: "GHS 600 — 3,500 / shipment",
    avatar: "AB",
    bio: "16 years clearing diaspora vehicle imports. GRA-licensed agent #CG-2148.",
    responseHours: 8,
    availableNow: true,
  },
  {
    id: "tr-6",
    name: "Fafa Adeli",
    profession: "Agricultural Extension Officer",
    region: "Volta · Eastern · Oti",
    rating: 4.88,
    jobsCompleted: 71,
    specialties: ["Poultry & livestock", "Farm audits", "Yield forecasting"],
    yearsActive: 8,
    licensed: true,
    verifiedBy: "Ministry of Food & Agriculture",
    feeRange: "GHS 500 — 1,800 / visit",
    avatar: "FA",
    bio: "MoFA-trained extension officer with drone surveying skills.",
    responseHours: 16,
    availableNow: true,
  },
];

export const FORENSIC_CASES: ForensicCase[] = [
  {
    id: "case-1",
    projectId: "east-legon-plot",
    title: "East Legon Hills — Title Overlap & Encroachment",
    status: "investigating",
    severity: "critical",
    openedAt: minus(11),
    lastUpdated: minus(2),
    lead: "Esi Ofori, Esq.",
    summary:
      "Lands Commission cross-check returned a competing claim from 2019 on the eastern 0.8-acre portion. Trustee A. Yawson confirmed third-party foundation works 14m inside the boundary. Stool elder signature on indenture diverges from reference set.",
    hypothesis:
      "The seller (stool elder Nii Agyemang) allegedly executed two indentures over overlapping parcels with two different buyers (2019 & 2025). Signatures on the 2025 indenture show 22% variance against 2019/2021 reference samples — possible third-party signature.",
    evidenceItemIds: ["doc-5", "doc-6", "ph-4", "al-3", "al-4", "al-5"],
    timeline: [
      { ts: minus(58), actor: "Ofori Legal Chambers", note: "Indenture uploaded" },
      { ts: minus(11), actor: "GhanaWatch AI", note: "Lands Commission cross-check returned competing claim (Case LC/GA/2019/0418)" },
      { ts: minus(8), actor: "Esi Ofori, Esq.", note: "Case opened — investigation phase initiated" },
      { ts: minus(4), actor: "Trustee A. Yawson", note: "On-site survey: encroachment confirmed at eastern boundary, photographed at 8 angles" },
      { ts: minus(3), actor: "Esi Ofori, Esq.", note: "Reference signature samples obtained from Lands Commission archive" },
      { ts: minus(2), actor: "GhanaWatch AI", note: "Signature ML comparison: 22% variance vs reference, above 18% threshold" },
    ],
    recommendedActions: [
      "File a caveat at the Lands Commission immediately (Form LC-7) to block any further dealings",
      "Issue a cease-and-desist to the encroaching developer",
      "Compile sealed evidence pack and forward to the Ghana Police Service Land Fraud Unit",
      "Open a parallel claim against the seller for breach + fraud (limitation under Limitation Act 1972, Act 54)",
      "Request judicial restraining order against further encroachment works",
    ],
    potentialLossGHS: 1250000,
  },
  {
    id: "case-2",
    projectId: "kasoa-4bed",
    title: "Kasoa — Receipt forensics + off-site photo cluster",
    status: "evidence-gathering",
    severity: "high",
    openedAt: minus(8),
    lastUpdated: minus(1),
    lead: "Kojo Owusu, MGhIS",
    summary:
      "Two flags in 8 days: (1) cement receipt with 41% authenticity (font + pixel tampering) and (2) a site photo with GPS 1.18 km off the registered parcel. Pattern suggests potential diversion of milestone funds.",
    hypothesis:
      "Manager (Kwame Mensah) may be inflating material receipts and submitting photos from a different site. Pattern matches the 'phantom progress' fraud profile common in Greater Accra / Central Region.",
    evidenceItemIds: ["doc-1", "ph-1", "al-1", "al-2"],
    timeline: [
      { ts: minus(8), actor: "GhanaWatch AI", note: "Cement receipt flagged: font inconsistency + pixel tampering (authenticity 41%)" },
      { ts: minus(5), actor: "Akosua Mensah", note: "Forensic case opened" },
      { ts: minus(4), actor: "GhanaWatch AI", note: "Vendor pattern cross-check: Diamond Cement issuing format mismatches prior 6 receipts" },
      { ts: minus(2), actor: "GhanaWatch AI", note: "Off-site photo flagged: GPS 1.18 km from parcel; scene mismatch 38%" },
      { ts: minus(1), actor: "Kojo Owusu, MGhIS", note: "Trustee dispatch scheduled for 2026-05-25; unannounced visit confirmed" },
    ],
    recommendedActions: [
      "Pause next milestone disbursement (Milestone 5: GHS 118,000)",
      "Trustee unannounced site visit — confirm presence of stage-5 work and material",
      "Request originals of all receipts in past 60 days for forensic review",
      "Phone-confirm vendor (Diamond Cement Ghana) — verify the GHS 14,400 invoice on their records",
    ],
    potentialLossGHS: 95000,
  },
];

export const FRAUD_PATTERNS: FraudPattern[] = [
  {
    id: "fp-double-sale",
    name: "Multi-buyer land double-sale",
    sector: "real-estate",
    region: "Greater Accra · Eastern · Central",
    prevalence: "endemic",
    signals: [
      "Seller pressing for quick payment, refusing to wait for Lands Commission cross-check",
      "Stool / family land with one signature only",
      "No site plan from a licensed surveyor",
      "Indenture cites a parcel reference that doesn't appear in LC's recent index",
      "Seller offers to keep the original indenture 'safe' until full payment clears",
    ],
    countermeasures: [
      "Lands Commission online search before any payment",
      "Independent licensed surveyor for boundary verification",
      "Conveyancing lawyer to vet the indenture & POAs",
      "Caveat filing if any suspicion arises",
      "Escrow with payment release contingent on registration",
    ],
    caseExamples: [
      "Dora Boateng v Mackeown Investments — single 20-acre plot found to also be part of a 50-acre sale to a developer",
      "Ghana Supreme Court cases of single plots sold to as many as 13 buyers",
    ],
    refUrl: "https://africanlii.org/article/20200326/chaotic-land-ownership-records-shock-ghanas-supreme-court",
  },
  {
    id: "fp-ghost-build",
    name: "Ghost construction / phantom progress",
    sector: "construction",
    region: "All regions — most common in peri-urban Accra & Kumasi",
    prevalence: "endemic",
    signals: [
      "Receipts arriving as phone photos / WhatsApp screenshots",
      "Progress photos taken at the same angle, edited timestamps",
      "Photos with stripped EXIF or GPS far from the parcel",
      "Material quantities inconsistent with the BOQ stage",
      "Funds requested 'in bulk' instead of milestone-tied",
    ],
    countermeasures: [
      "BOQ-anchored milestone escrow",
      "Geo-stamped photos through the GhanaWatch app only",
      "Trustee QS visit at each milestone boundary",
      "Drone overhead audit for sites > 0.5 acre",
      "Random unannounced trustee visits",
    ],
    caseExamples: [
      "Toronto diaspora family — £42,000 sent for Kasoa home; 14 months later, only foundation laid",
      "London diaspora — GHS 380,000 sent for 'twin-house build' in Adenta; receipts photographed against fabric backdrop",
    ],
  },
  {
    id: "fp-fake-poa",
    name: "Fake / unnotarised power of attorney",
    sector: "real-estate",
    region: "Greater Accra & Ashanti",
    prevalence: "common",
    signals: [
      "POA presented as a printed letter without notarial seal",
      "Holder cannot produce an apostille (for diaspora-issued POAs)",
      "Stamp visible but issuer/notary not on the register",
      "Holder pushes for cash settlement",
    ],
    countermeasures: [
      "Cross-check notary on the General Legal Council registry",
      "Require apostille for any POA issued abroad",
      "Direct call to the principal (overseas) via verified number",
      "Refuse any cash settlement above GHS 5,000",
    ],
    caseExamples: [
      "USA-based diaspora — GHS 220,000 paid for plot via 'cousin' holding a typed POA; principal had never signed",
    ],
  },
  {
    id: "fp-duty-uplift",
    name: "Tema port last-minute duty uplift",
    sector: "vehicle-import",
    region: "Tema · Takoradi",
    prevalence: "common",
    signals: [
      "Clearing agent adds GHS 5,000+ 'penalty' after vehicle has landed",
      "Penalty receipt not on GRA letterhead / no QR / no serial",
      "Pressure to pay outside GRA portal",
      "Different duty figure than the GRA HS-code calculator",
    ],
    countermeasures: [
      "Run the GRA HS duty calculator independently before shipment",
      "Demand serialised GRA receipts with QR codes for every line item",
      "Verify clearing agent on GRA Customs Division registry",
      "Refuse payment outside GhanaWatch escrow",
    ],
    caseExamples: [
      "Sydney diaspora — GHS 18,000 'penalty' demanded on Tema-cleared Civic; refunded after GhanaWatch challenge",
    ],
  },
  {
    id: "fp-duplicate-receipt",
    name: "Duplicate-signature receipt fraud",
    sector: "business",
    region: "All regions",
    prevalence: "common",
    signals: [
      "Two receipts with >90% signature pixel-hash match",
      "Receipts on plain paper without vendor letterhead",
      "Same vendor name with inconsistent stamp",
      "Round-number 'top-up' amounts each month",
    ],
    countermeasures: [
      "Document forensics: duplicate-hash detection at upload",
      "Vendor letterhead requirement",
      "MoMo merchant ID verification",
      "Direct payment to vendor via traceable channel",
    ],
    caseExamples: [
      "Hamburg diaspora — GHS 36,000 in 'rent top-ups' over 7 months; signatures matched 94%; landlord never received funds",
    ],
  },
  {
    id: "fp-funeral-inflation",
    name: "Funeral cost inflation cluster",
    sector: "funeral",
    region: "All regions — most acute in Western, Ashanti, Central",
    prevalence: "endemic",
    signals: [
      "Canopy / PA / catering quotes 30%+ above regional benchmark",
      "Vendor MoMo IDs that do not resolve",
      "'Family levy' with no contributor ledger",
      "Mortuary bills above the published fee schedule",
      "Cash demanded for hearse / drumming, no receipts",
    ],
    countermeasures: [
      "Vendor benchmarking against GhanaWatch's regional database",
      "MoMo merchant ID resolution check",
      "Contributor ledger required",
      "Trustee attends planning meeting + reconciles spend",
    ],
    caseExamples: [
      "Bristol diaspora — funeral budget escalated from GHS 24,000 to GHS 71,000 over 6 weeks with no itemised tally",
    ],
  },
  {
    id: "fp-hospital-ransom",
    name: "Hospital body-release ransom",
    sector: "medical",
    region: "Greater Accra · Ashanti",
    prevalence: "common",
    signals: [
      "Pressure to pay outside the official hospital cashier",
      "Round-number bills with no itemisation",
      "Additional 'release fees' that aren't on the receipt",
      "Drugs sourced from outside the hospital pharmacy at inflated prices",
    ],
    countermeasures: [
      "Direct cashier settlement",
      "Itemised bill requirement",
      "Trustee ward visit + receipt validation",
      "Hospital portal cross-check",
    ],
    caseExamples: [
      "Sydney diaspora — body of late grandfather held at Korle Bu mortuary pending GHS 4,500 'release fee' — not on the receipt",
    ],
  },
  {
    id: "fp-school-fake",
    name: "School fees forgery / ghost enrolment",
    sector: "education",
    region: "All regions",
    prevalence: "common",
    signals: [
      "Receipts that don't match the school's portal records",
      "'Extra classes' invoiced without school authorisation",
      "Books / uniforms quoted at retail when school has a bulk-discount supplier",
      "Term receipts without serial number",
    ],
    countermeasures: [
      "School portal cross-check (GES & private databases)",
      "Trustee attendance attestation",
      "Direct settlement to school account where supported",
      "Bulk-supplier price benchmarking",
    ],
    caseExamples: [
      "Manchester diaspora — GHS 24,000 in 'fees' over 18 months for child no longer enrolled",
    ],
  },
];

export const BENCHMARKS: Benchmark[] = [
  { id: "bm-1", category: "material", item: "Cement (Diamond, 50kg)", unit: "bag", region: "Greater Accra", medianGHS: 105, p10: 95, p90: 118, updated: minus(2).slice(0,10) },
  { id: "bm-2", category: "material", item: "Iron Rod 12mm", unit: "rod (12m)", region: "Greater Accra", medianGHS: 165, p10: 150, p90: 185, updated: minus(2).slice(0,10) },
  { id: "bm-3", category: "material", item: "Aluminium Roofing Sheet", unit: "sqm", region: "All regions", medianGHS: 95, p10: 82, p90: 108, updated: minus(3).slice(0,10) },
  { id: "bm-4", category: "labor", item: "Mason Day Rate", unit: "day", region: "Greater Accra", medianGHS: 220, p10: 180, p90: 280, updated: minus(7).slice(0,10) },
  { id: "bm-5", category: "labor", item: "Carpenter Day Rate", unit: "day", region: "Ashanti", medianGHS: 200, p10: 170, p90: 250, updated: minus(7).slice(0,10) },
  { id: "bm-6", category: "import-duty", item: "Honda Civic 2018-2020 Duty", unit: "vehicle", region: "Tema", medianGHS: 36800, p10: 33000, p90: 41500, updated: minus(2).slice(0,10) },
  { id: "bm-7", category: "funeral", item: "Canopy + 200 chairs (1 day)", unit: "rental", region: "Western", medianGHS: 6080, p10: 4800, p90: 7800, updated: minus(5).slice(0,10) },
  { id: "bm-8", category: "funeral", item: "Casket (mid-range)", unit: "unit", region: "All regions", medianGHS: 5400, p10: 3800, p90: 9500, updated: minus(10).slice(0,10) },
  { id: "bm-9", category: "medical", item: "Korle Bu — Day-case surgery", unit: "case", region: "Greater Accra", medianGHS: 8500, p10: 5200, p90: 14000, updated: minus(14).slice(0,10) },
  { id: "bm-10", category: "education", item: "SHS boarding (term)", unit: "term", region: "Northern", medianGHS: 2400, p10: 2100, p90: 2900, updated: minus(21).slice(0,10) },
];

export const NOTIFICATIONS: Notification[] = [
  { id: "n-1", kind: "alert", severity: "critical", title: "Off-site photo on Kasoa build", body: "Today's photo is 1.18 km from the parcel. Trustee dispatch recommended.", ts: minus(2, 4), projectId: "kasoa-4bed", read: false },
  { id: "n-2", kind: "alert", severity: "critical", title: "Encroachment confirmed — East Legon", body: "Trustee A. Yawson photographed third-party foundation 14m inside boundary.", ts: minus(4), projectId: "east-legon-plot", read: false },
  { id: "n-3", kind: "verify", severity: "warning", title: "Document forensics: 41% authenticity", body: "Cement receipt (GHS 14,400) shows font inconsistency + pixel tampering.", ts: minus(3), projectId: "kasoa-4bed", read: false },
  { id: "n-4", kind: "trustee", severity: "info", title: "Trustee accepted dispatch", body: "Kojo Owusu has accepted the Kasoa milestone-5 re-verification. ETA 2026-05-25.", ts: minus(1), projectId: "kasoa-4bed", read: true },
  { id: "n-5", kind: "milestone", severity: "info", title: "Milestone released", body: "Ho poultry farm — Milestone 2 (GHS 14,000) released after Trustee F. Adeli's verification.", ts: minus(3), projectId: "ho-poultry", read: true },
  { id: "n-6", kind: "doc", severity: "info", title: "Document verified", body: "Korle Bu pre-op bill (GHS 18,500) — 99% authenticity, cross-matched with hospital portal.", ts: minus(15), projectId: "korle-bu-care", read: true },
  { id: "n-7", kind: "ledger", severity: "info", title: "Audit ledger anchored", body: "Daily audit hash committed: 0xae34f8…91d2c0", ts: minus(1), read: true },
  { id: "n-8", kind: "alert", severity: "warning", title: "Funeral quote above benchmark", body: "Canopy + PA quote for Takoradi funeral 38% above regional median.", ts: minus(6), projectId: "takoradi-funeral", read: false },
  { id: "n-9", kind: "verify", severity: "warning", title: "Duplicate receipt detected", body: "Kumasi shop rent top-up signature matches October batch at 94%.", ts: minus(5), projectId: "kumasi-shop", read: false },
  { id: "n-10", kind: "system", severity: "info", title: "Weekly trust report ready", body: "Your portfolio trust score moved from 76 → 73 this week. Two projects worsened.", ts: minus(1), read: false },
];

export const getProject = (id: string) => PROJECTS.find((p) => p.id === id);
export const getDocsByProject = (id: string) => DOCUMENTS.filter((d) => d.projectId === id);
export const getPhotosByProject = (id: string) => SITE_PHOTOS.filter((p) => p.projectId === id);
export const getMilestonesByProject = (id: string) => MILESTONES.filter((m) => m.projectId === id);
export const getAlertsByProject = (id: string) => ALERTS.filter((a) => a.projectId === id);
export const getAuditByProject = (id: string) =>
  AUDIT_EVENTS.filter((e) => e.projectId === id).sort((a, b) => (a.ts < b.ts ? 1 : -1));
export const getCase = (id: string) => FORENSIC_CASES.find((c) => c.id === id);
export const getCasesByProject = (id: string) => FORENSIC_CASES.filter((c) => c.projectId === id);

export const PLATFORM_STATS = {
  remittancesTracked2025GHS: 18_400_000,
  fraudPrevented2025GHS: 2_180_000,
  documentsAnalyzed: 14_872,
  flagsRaised: 612,
  trusteesActive: 1_240,
  diasporaUsers: 8_950,
  projectsActive: 1_487,
  forensicCasesOpen: 38,
  countriesServed: 47,
};

// Regional risk heatmap data
export const REGION_RISK: Record<string, { riskScore: number; activeProjects: number; openCases: number }> = {
  "Greater Accra": { riskScore: 68, activeProjects: 612, openCases: 19 },
  "Ashanti": { riskScore: 54, activeProjects: 311, openCases: 9 },
  "Central": { riskScore: 49, activeProjects: 178, openCases: 4 },
  "Western": { riskScore: 41, activeProjects: 102, openCases: 2 },
  "Eastern": { riskScore: 43, activeProjects: 88, openCases: 3 },
  "Volta": { riskScore: 28, activeProjects: 74, openCases: 1 },
  "Northern": { riskScore: 22, activeProjects: 56, openCases: 0 },
  "Bono": { riskScore: 30, activeProjects: 41, openCases: 0 },
  "Upper East": { riskScore: 19, activeProjects: 18, openCases: 0 },
  "Upper West": { riskScore: 17, activeProjects: 7, openCases: 0 },
  "Oti": { riskScore: 25, activeProjects: 12, openCases: 0 },
  "Western North": { riskScore: 26, activeProjects: 14, openCases: 0 },
  "Bono East": { riskScore: 29, activeProjects: 22, openCases: 0 },
  "Ahafo": { riskScore: 24, activeProjects: 9, openCases: 0 },
  "Savannah": { riskScore: 21, activeProjects: 11, openCases: 0 },
  "North East": { riskScore: 20, activeProjects: 7, openCases: 0 },
};

// ---- Human review queue ----
export const HUMAN_REVIEWS: HumanReview[] = [
  {
    id: "hr-1",
    caseId: "case-1",
    projectId: "east-legon-plot",
    reviewer: { id: "an-1", name: "Ama Sarpong", role: "Senior Forensic Analyst", license: "Bar-GH 2014-822" },
    status: "pending",
    aiVerdict: "Title overlap + signature variance + on-site encroachment — high confidence fraud pattern.",
    aiConfidence: 92,
    slaHours: 6,
    evidenceReviewed: 0,
    priority: "critical",
  },
  {
    id: "hr-2",
    caseId: "case-2",
    projectId: "kasoa-4bed",
    reviewer: { id: "an-2", name: "Kwesi Adjei", role: "Construction Forensic Analyst", license: "GhIS 2017-441" },
    status: "approved",
    aiVerdict: "Receipt forensics + off-site photo cluster — likely diverted milestone funds.",
    aiConfidence: 78,
    analystVerdict: "Confirmed — recommend pausing M5 disbursement and dispatching trustee for surprise audit.",
    analystNote: "I reviewed the cement receipt against 6 prior verified Diamond Cement receipts. Font shift confirmed. Pattern matches a phantom-progress case I worked in 2024. Aligned with AI recommendation.",
    decisionAt: minus(1),
    slaHours: 24,
    evidenceReviewed: 8,
    priority: "high",
  },
  {
    id: "hr-3",
    caseId: "case-1",
    projectId: "east-legon-plot",
    reviewer: { id: "an-1", name: "Ama Sarpong", role: "Senior Forensic Analyst", license: "Bar-GH 2014-822" },
    status: "more-evidence",
    aiVerdict: "Stool elder signature variance: 22% vs reference samples.",
    aiConfidence: 71,
    analystVerdict: "Inconclusive without 3 more reference samples from 2018-2020.",
    analystNote: "Requesting the LC archive team to pull 3 more samples. Will reconvene Friday.",
    decisionAt: minus(3),
    slaHours: 48,
    evidenceReviewed: 5,
    priority: "high",
  },
];

// ---- Signatories per project ----
export const SIGNATORIES: Record<string, Signatory[]> = {
  "kasoa-4bed": [
    { id: "sg-1", name: "Akosua Mensah", role: "diaspora-owner", status: "signed", verifiedIdentity: true, contact: "akosua@example.com", signedAt: minus(140) },
    { id: "sg-2", name: "Mr. Joseph Mensah", role: "next-of-kin", status: "signed", verifiedIdentity: true, contact: "+233 24 555 0142", signedAt: minus(139) },
    { id: "sg-3", name: "Kojo Owusu, MGhIS", role: "trustee", status: "signed", verifiedIdentity: true, contact: "kojo.owusu@trustee.gw", signedAt: minus(95) },
    { id: "sg-4", name: "Esi Ofori, Esq.", role: "lawyer", status: "pending", verifiedIdentity: true, contact: "esi@oforilegal.gh" },
  ],
  "east-legon-plot": [
    { id: "sg-5", name: "Nana Yaw Boateng", role: "diaspora-owner", status: "signed", verifiedIdentity: true, contact: "nanayaw@example.com", signedAt: minus(60) },
    { id: "sg-6", name: "Aunt Akua Boateng", role: "next-of-kin", status: "signed", verifiedIdentity: true, contact: "+233 20 555 0188", signedAt: minus(59) },
    { id: "sg-7", name: "Esi Ofori, Esq.", role: "lawyer", status: "signed", verifiedIdentity: true, contact: "esi@oforilegal.gh", signedAt: minus(58) },
    { id: "sg-8", name: "Akua Yawson", role: "trustee", status: "signed", verifiedIdentity: true, contact: "akua@yawsonsurvey.gh", signedAt: minus(4) },
    { id: "sg-9", name: "Auntie Esther (witness)", role: "witness", status: "declined", verifiedIdentity: false, contact: "+233 27 555 9982" },
  ],
};

// ---- Trustee applications (accreditation pipeline) ----
export const TRUSTEE_APPLICATIONS: TrusteeApplication[] = [
  { id: "ta-1", applicant: "Yaw Asare", profession: "Quantity Surveyor", yearsExperience: 12, region: "Ashanti", licenseAuthority: "Ghana Institution of Surveyors", licenseNumber: "GhIS-2013-1041", stage: "skill-test", appliedAt: minus(4) },
  { id: "ta-2", applicant: "Doris Asiedu", profession: "Conveyancing Lawyer", yearsExperience: 7, region: "Greater Accra", licenseAuthority: "General Legal Council", licenseNumber: "GLC-2018-3309", stage: "references", appliedAt: minus(11) },
  { id: "ta-3", applicant: "Kwame Tetteh", profession: "Customs Clearing Agent", yearsExperience: 15, region: "Tema", licenseAuthority: "GRA / Customs Division", licenseNumber: "CG-2010-118", stage: "background-check", appliedAt: minus(2) },
  { id: "ta-4", applicant: "Dr. Adwoa Aidoo", profession: "Medical Care Coordinator", yearsExperience: 20, region: "Greater Accra", licenseAuthority: "Medical & Dental Council", licenseNumber: "MDC-2005-0917", stage: "approved", appliedAt: minus(60) },
];

// ---- Live activity feed (rolling) ----
export const LIVE_EVENTS: LiveEvent[] = [
  { id: "le-1", ts: minus(0, 0.1), category: "verify", message: "Diamond Cement receipt verified for project 'Tamale 3-Bed Build' (98% authenticity)", region: "Northern", amountGHS: 4250 },
  { id: "le-2", ts: minus(0, 0.2), category: "site", message: "Drone overhead by trustee F. Adeli — Ho poultry farm coop roofing 80% confirmed", region: "Volta" },
  { id: "le-3", ts: minus(0, 0.3), category: "kyc", message: "Diaspora user verified — Ghana Card + selfie liveness passed", region: "Greater Accra" },
  { id: "le-4", ts: minus(0, 0.6), category: "case", message: "Forensic case opened — duplicate-receipt pattern in Adum business setup", region: "Ashanti" },
  { id: "le-5", ts: minus(0, 1), category: "payment", message: "Milestone 4 released for Kasoa 4-Bed Build (GHS 140,000) — trustee verified", region: "Central", amountGHS: 140000 },
  { id: "le-6", ts: minus(0, 1.5), category: "doc", message: "Bill of Lading verified for Tema-bound shipment (Volkswagen Passat)", region: "Greater Accra" },
  { id: "le-7", ts: minus(0, 2), category: "trustee", message: "Trustee Kojo Owusu accepted dispatch (Kasoa M5 re-verification, ETA 24h)", region: "Central" },
  { id: "le-8", ts: minus(0, 3), category: "system", message: "Daily audit ledger hash committed (0xae34f8…91d2c0)" },
  { id: "le-9", ts: minus(0, 4), category: "verify", message: "Korle Bu surgery bill cross-matched with hospital portal — 99% confidence", region: "Greater Accra", amountGHS: 18500 },
  { id: "le-10", ts: minus(0, 5), category: "site", message: "Off-parcel photo flagged on Kumasi shop fit-out (1.4 km off registered address)", region: "Ashanti" },
];

// ---- Hometown rooms ----
export const HOMETOWN_ROOMS: HometownRoom[] = [
  {
    id: "ht-1",
    name: "Kasoa Sons & Daughters (Toronto)",
    region: "Central",
    members: 184,
    activeProjects: 27,
    pooledGHS: 612000,
    description: "Diaspora from Kasoa & environs based in the GTA. We co-fund 3 community projects + verify each other's individual builds.",
    lastMessage: { actor: "Akosua M.", text: "Trustee Kojo did the M4 visit on Saturday — drone footage is in the ledger.", ts: minus(0, 6) },
    verified: true,
  },
  {
    id: "ht-2",
    name: "Adum Trade Collective (Hamburg)",
    region: "Ashanti",
    members: 56,
    activeProjects: 14,
    pooledGHS: 224000,
    description: "Hamburg-based traders pooling capital for stalls in Adum and Asafo markets.",
    lastMessage: { actor: "Esi F.", text: "Auntie Grace got the duplicate-receipt flag again. We need to talk.", ts: minus(0, 11) },
    verified: true,
  },
  {
    id: "ht-3",
    name: "Ho Vol-Tribes (Atlanta)",
    region: "Volta",
    members: 89,
    activeProjects: 19,
    pooledGHS: 388000,
    description: "Volta diaspora in the US South. Poultry, cassava, smoked fish — agriculture-first.",
    lastMessage: { actor: "Mawuli A.", text: "Drone confirms coop dimensions. M3 release approved.", ts: minus(1) },
    verified: true,
  },
  {
    id: "ht-4",
    name: "East Legon Hills Owners (London)",
    region: "Greater Accra",
    members: 312,
    activeProjects: 44,
    pooledGHS: 4_120_000,
    description: "Diaspora owners of plots in East Legon Hills, Adjiringanor, Trasacco-adjacent estates.",
    lastMessage: { actor: "Nana Yaw B.", text: "If your indenture was issued via Nii Agyemang 2023-2025, please DM. Possible cluster.", ts: minus(0, 18) },
    verified: true,
  },
  {
    id: "ht-5",
    name: "Tamale Family Network (Manchester)",
    region: "Northern",
    members: 41,
    activeProjects: 9,
    pooledGHS: 86000,
    description: "Tamale-area diaspora in the North-West UK. School fees, medical, small business.",
    lastMessage: { actor: "Hawa M.", text: "TaSec fees verified. Bro Yakubu attended PTA, photo + signed form on ledger.", ts: minus(2) },
    verified: false,
  },
];

// Portfolio-level time series
export const PORTFOLIO_TRUST_HISTORY = genSeries(90, 65, 4, 0.15);
export const PORTFOLIO_RISK_HISTORY = genSeries(90, 35, 4, -0.05);
export const PORTFOLIO_SPEND_HISTORY = (() => {
  const out: { d: string; v: number }[] = [];
  let v = 1200000;
  for (let i = 90; i >= 0; i--) {
    v += 8000 + Math.abs(Math.sin(i / 4) * 12000) + (i % 7 === 0 ? 25000 : 0);
    out.push({ d: minus(i).slice(0, 10), v: Math.round(v / 1000) });
  }
  return out;
})();
